spring.application.name=playlist-porter

#db
spring.datasource.url=jdbc:postgresql://localhost:5432/playlist_porter
spring.datasource.username=pp_user
spring.datasource.password=pp_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# CORS (so React on 5173 can talk to Spring on 8080)
app.cors.allowed-origins=http://localhost:5173