spring.application.name=playlist-porter

#db
spring.datasource.url=jdbc:postgresql://localhost:5432/playlist_porter
spring.datasource.username=pp_user
spring.datasource.password=pp_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# CORS (so React on 5173 can talk to Spring on 8080)
app.cors.allowed-origins=http://localhost:5173

# Spotify OAuth
spotify.client-id=${SPOTIFY_CLIENT_ID}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
spotify.redirect-uri=http://localhost:8080/api/auth/spotify/callback
spotify.scopes=playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-read-private,user-read-email

# YouTube OAuth
youtube.client-id=${YOUTUBE_CLIENT_ID}
youtube.client-secret=${YOUTUBE_CLIENT_SECRET}
youtube.redirect-uri=http://localhost:8080/api/auth/youtube/callback
youtube.scopes=https://www.googleapis.com/auth/youtube

# JWT (we use this to identify logged-in users in our own app)
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000